name: N-DS64 project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    permissions:
      contents: write
    env:
      DEVKITPRO: /opt/devkitpro
      DEVKITARM: /opt/devkitpro/devkitARM

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Debug
        run: |
          gcc -E archivo.c | grep -v '^#' | grep -E '^[a-zA-Z_][a-zA-Z0-9_* ]+[ ]+[a-zA-Z_][a-zA-Z0-9_]+\s*\(' | sed 's/^[ \t]*//' | sort -u > funciones_limpias.txt


      - name: Compile project
        run: |
          export PATH=$DEVKITARM/bin:$DEVKITPRO/tools/bin:$PATH
          export PATH=$DEVKITARM/bin:$DEVKITPRO/bin:$PATH
          make -j$(nproc) V=1
        shell: bash
        
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: 'N-DS64'
          path: "**/*.nds"
          if-no-files-found: warn
         
      - name: Release NDS Rom
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          files: "**/*.nds" "funciones_limpias.txt"
          tag_name: latest
          name: "N-DS64 Ultima Compilación"
          body: "nothing"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

